---
version: 2.1
jobs:
  lint_and_test_code:
    docker:
      - image: python:3.7.6-buster
    steps:
      - checkout
      - run:
          name: Install build & test dependencies
          command: |
            pip3 install --progress-bar off 'poetry==1.0.3' 'pre-commit==1.20.0'
            poetry config --no-interaction virtualenvs.create false
            apt-get update && apt-get install shellcheck
      - run:
          name: Build & install
          command: poetry build && poetry install
      - run:
          name: Run pre-commit hooks on all files
          command: pre-commit run --all-files --show-diff-on-failure
      - run:
          name: Set up test reporting
          command: |
            curl -L https://s3.amazonaws.com/codeclimate/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            sha256sum --check ./.circleci/cc-test-reporter.sha256sum
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
            poetry run pytest --full-trace --cov-report=xml:coverage.xml
      - store_test_results:
          path: coverage.xml
      - store_artifacts:
          path: dist
      - run:
          name: Publish test results
          command: ./cc-test-reporter after-build --coverage-input-type coverage.py
      - run:
          name: Run integration test
          command: |
            poetry run isup google.com
workflows:
  version: 2.1
  pipeline:
    jobs:
      - lint_and_test_code
