---
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install build & test dependencies
        run: |
          pip3 install --disable-pip-version-check --progress-bar off 'poetry'
          poetry install --no-ansi --no-interaction
      - name: Run linters
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install build & test dependencies
        run: |
          pip3 install --disable-pip-version-check --progress-bar off 'poetry'
      - name: Cache dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Build & install
        run: |
          poetry build --no-ansi --no-interaction && \
          poetry install --no-ansi --no-interaction
      - name: Run tests
        run: poetry run pytest --full-trace
      - name: Test basic cli elements
        run: |
          ( set -x ; poetry run isup --version )
          ( set -x ; poetry run isup --help )
