---
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - name: Install build & test dependencies
        run: |
          pip3 install --disable-pip-version-check --progress-bar off 'poetry'
          poetry install --no-ansi --no-interaction
      - name: Run linters
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - name: Install build & test dependencies
        run: |
          pip3 install --disable-pip-version-check --progress-bar off 'poetry'
      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Build & install
        run: |
          poetry build --no-ansi --no-interaction && \
          poetry install --no-ansi --no-interaction
      - name: Run tests
        run: poetry run pytest --full-trace
      - name: Test basic cli elements
        run: |
          ( set -x ; poetry run isup --version )
          ( set -x ; poetry run isup --help )
